### ISSUE TITLE
May you please share the weight or the data?

### ISSUE THREAD

**Issue by noticeable** [EricSchuMa/PYOLO#1]
Hello,
       Thanks for your share of your project, however, I can't find the weights or the data about your project,May you please share me that?

**Comment by EricSchuMa** [comment]
Hello noticeable, 
the data is publicly available at [https://bdd-data.berkeley.edu/](https://bdd-data.berkeley.edu/).
You can download the checkpoint for our best results from 
[https://drive.google.com/file/d/1GLpDj9t3Mo54_pTy6ZK_plNwoP9cX766/view?usp=sharing](https://drive.google.com/file/d/1GLpDj9t3Mo54_pTy6ZK_plNwoP9cX766/view?usp=sharing). This model was trained with the yolov3-custom.cfg found in the repository and will not work for other setups. If you have additional questions feel free to ask!
